-- 1. FRED 전용 일 단위 지표 테이블(indicator_fred_daily_logs) 생성
-- 기존 통합 테이블(indicator_daily_logs)과 분리하여 독립적으로 관리합니다.
create table IF NOT EXISTS public.indicator_fred_daily_logs (
  id bigint generated by default as identity not null,
  category text null default 'Macro/Energy'::text,
  fred_wti double precision null,
  fred_brent double precision null,
  fred_usd_index double precision null,
  fred_treasury_10y double precision null,
  unit text null default 'index/usd'::text,
  reference_date text not null,
  collected_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint indicator_fred_daily_logs_pkey primary key (id),
  constraint indicator_fred_daily_date_unique unique (reference_date)
) TABLESPACE pg_default;

-- 2. 새로운 월 단위 지표 테이블(indicator_fred_monthly_logs)
create table IF NOT EXISTS public.indicator_fred_monthly_logs (
  id bigint generated by default as identity not null,
  category text null default 'Macro/Supply Chain'::text,
  fred_gepu double precision null,
  unit text null default 'index'::text,
  reference_month text not null, -- 포맷 예시: 'YYYY-MM'
  collected_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint indicator_fred_monthly_logs_pkey primary key (id),
  constraint indicator_fred_monthly_month_unique unique (reference_month)
) TABLESPACE pg_default;

-- GSCPI 테이블에도 업데이트 시간 트리거 등을 설정할 경우 추가 (선택 사항)
-- create trigger update_indicator_monthly_modtime BEFORE
-- update on indicator_monthly_logs for EACH row
-- execute FUNCTION update_modified_column();
